## Libraries

In [146]:
import pandas as pd
import numpy as np

## Loading Dataframes

In [147]:
df_demo = pd.read_csv('data/df_final_demo.txt')
df_final_experiment = pd.read_csv('data/df_final_experiment_clients.txt')
df_final_web_1 = pd.read_csv('data/df_final_web_data_pt_1.txt')
df_final_web_2 = pd.read_csv('data/df_final_web_data_pt_2.txt')

In [148]:
df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [149]:
df_final_experiment

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
70604    2443347       NaN
70605    8788427       NaN
70606     266828       NaN
70607    1266421       NaN
70608    9895983       NaN

[70609 rows x 2 columns]

In [150]:
df_final_web_1

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
343136,2443347,465784886_73090545671,136329900_10529659391_316129,confirm,2017-03-31 15:15:46
343137,2443347,465784886_73090545671,136329900_10529659391_316129,step_3,2017-03-31 15:14:53
343138,2443347,465784886_73090545671,136329900_10529659391_316129,step_2,2017-03-31 15:12:08
343139,2443347,465784886_73090545671,136329900_10529659391_316129,step_1,2017-03-31 15:11:37
343140,2443347,465784886_73090545671,136329900_10529659391_316129,start,2017-03-31 15:10:47

In [151]:
df_final_web_2

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58
...,...,...,...,...,...
412259,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
412260,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
412261,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
412262,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
412263,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [152]:
# Merge the two web dataframes into one
df_final_web_1_and_2 = pd.concat([df_final_web_1, df_final_web_2], ignore_index=True)

In [153]:
df_final_web_1_and_2

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

## Phase 1 — EDA & Data Cleaning

#### Remove duplicates

Let's remove duplicates from all dfs before continuing

In [154]:
df_demo = df_demo.drop_duplicates()
df_final_experiment = df_final_experiment.drop_duplicates()
df_final_web_1_and_2 = df_final_web_1_and_2.drop_duplicates()

In [155]:
df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [156]:
df_final_experiment

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
70604    2443347       NaN
70605    8788427       NaN
70606     266828       NaN
70607    1266421       NaN
70608    9895983       NaN

[70609 rows x 2 columns]

In [157]:
df_final_web_1_and_2

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

#### Nulls

In the dataframes, as per showed with 'Data Wrangler' extension, there are a lot of customers not assigned to groups and some nulls in the demo df. Let's explore that.

In [158]:
def null_report(df):
    '''Sum of null values and percentage of null values for each column in a dataframe.'''
    return pd.DataFrame({
        "column": df.columns,
        "nulls": df.isna().sum().values,
        "percent": (df.isna().mean() * 100).round(2).values
    })

In [159]:
nulls_demo = null_report(df_demo)
print("Nulls in df_demo:")
print(nulls_demo)
nulls_experiment = null_report(df_final_experiment)
print("\nNulls in df_final_experiment:")
print(nulls_experiment)
nulls_web_1_and_2 = null_report(df_final_web_1_and_2)
print("\nNulls in df_final_web_1_and_2:")
print(nulls_web_1_and_2)

Nulls in df_demo:
             column  nulls  percent
0         client_id      0     0.00
1    clnt_tenure_yr     14     0.02
2  clnt_tenure_mnth     14     0.02
3          clnt_age     15     0.02
4             gendr     14     0.02
5         num_accts     14     0.02
6               bal     14     0.02
7      calls_6_mnth     14     0.02
8     logons_6_mnth     14     0.02

Nulls in df_final_experiment:
      column  nulls  percent
0  client_id      0     0.00
1  Variation  20109    28.48

Nulls in df_final_web_1_and_2:
         column  nulls  percent
0     client_id      0      0.0
1    visitor_id      0      0.0
2      visit_id      0      0.0
3  process_step      0      0.0
4     date_time      0      0.0

As we can see not all clients are part of the experiment with an about 30% of them without group assigned

In [160]:
overview = pd.DataFrame({
    "column": df_final_experiment.columns,
    "not_nulls": df_final_experiment.notna().sum().values,
    "nulls": df_final_experiment.isna().sum().values
})

overview

      column  not_nulls  nulls
0  client_id      70609      0
1  Variation      50500  20109

So only 50K of the clients are part of the experiment. Being known that, the strategy that we will follow is to eliminate their records from everywhere first.

In [161]:
ids_to_exclude = df_final_experiment.loc[df_final_experiment["Variation"].isna(), "client_id"].unique()
print(ids_to_exclude)
print(len(ids_to_exclude)) #To verify the number of unique client_ids with null Variation values

[5459747 8031000 1847030 ...  266828 1266421 9895983]
20109

In [162]:
# Remove all rows in df1, df2, and df3 whose client_id is in bad_ids
# using the client IDs collected from the raw table with null values

df_demo_no_nulls = df_demo[~df_demo["client_id"].isin(ids_to_exclude)].copy()
df_final_experiment_no_nulls = df_final_experiment[~df_final_experiment["client_id"].isin(ids_to_exclude)].copy()
df_final_web_1_and_2_no_nulls = df_final_web_1_and_2[~df_final_web_1_and_2["client_id"].isin(ids_to_exclude)].copy()

In [163]:
df_final_experiment_no_nulls

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
50495     393005   Control
50496    2908510   Control
50497    7230446      Test
50498    5230357      Test
50499    6334360      Test

[50500 rows x 2 columns]

So this matches with the previously 50K clients assigned

In [164]:
df_demo_no_nulls

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
50495,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0
50496,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0
50497,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0
50498,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0

It has some values missing. As it is a small percentage, let's drop them.

In [165]:
df_demo_no_nulls = df_demo_no_nulls.dropna(how="any")
df_demo_no_nulls

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
50495,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0
50496,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0
50497,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0
50498,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0

In [166]:
df_merged = df_demo_no_nulls.merge(
    df_final_experiment_no_nulls,
    on="client_id",
    how="inner"
)

In [167]:
df_final_web_1_and_2_no_nulls

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

Finally, we keep only the web records whose  client_id  also appears in the experiment table. Any web row without a matching client in the experiment dataset is removed.

In [168]:
df_final_web_1_and_2_clean = df_final_web_1_and_2_no_nulls[
    df_final_web_1_and_2_no_nulls["client_id"].isin(df_final_experiment_no_nulls["client_id"])
].copy()

df_final_web_1_and_2_clean

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
637487,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27
637532,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17
637533,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31
637534,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23
637535,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20

In [169]:
print(df_final_web_1_and_2_no_nulls['client_id'].nunique())
print(df_final_web_1_and_2_clean['client_id'].nunique())

100048
50500

So the dataset has fallen 50% almost but we are having the same amount of unique csts ids.

### Casting date-time

In [170]:
df_final_web_1_and_2_clean["date_time"] = pd.to_datetime(df_final_web_1_and_2_clean["date_time"])
df_final_web_1_and_2_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317235 entries, 0 to 637535
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     317235 non-null  int64
 1   visitor_id    317235 non-null  object
 2   visit_id      317235 non-null  object
 3   process_step  317235 non-null  object
 4   date_time     317235 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 14.5+ MB

## Exploring data

### Demographics

In [171]:
#This is as for now the only demographic that is categorical, so we will create a frequency table for it.
gender_table = pd.crosstab(df_merged["gendr"], columns="Count")
gender_table["%"] = (gender_table["Count"] / gender_table["Count"].sum() * 100).round(2)
gender_table

col_0  Count      %
gendr
F      16258  32.20
M      16947  33.57
U      17280  34.23
X          2   0.00

In [172]:
df_merged.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,5.048700e+04,50487.000000,50487.000000,50487.000000,50487.000000,5.048700e+04,50487.000000,50487.000000
mean,5.006180e+06,12.031810,150.416365,47.319795,2.254580,1.495168e+05,3.093272,6.131856
std,2.877445e+06,6.860326,81.945403,15.518616,0.533675,3.020390e+05,2.188009,2.175441
min,5.550000e+02,2.000000,33.000000,17.000000,1.000000,2.378944e+04,0.000000,3.000000
25%,2.515688e+06,6.000000,82.000000,33.500000,2.000000,3.987718e+04,1.000000,4.000000
50%,5.025043e+06,11.000000,136.000000,48.000000,2.000000,6.573433e+04,3.000000,6.000000
75%,7.477922e+06,16.000000,192.000000,59.500000,2.000000,1.399583e+05,5.000000,8.000000
max,9.999832e+06,55.000000,669.000000,96.000000,7.000000,1.632004e+07,6.000000,9.000000

In [180]:
# We are using median instead of mean because the data is skewed, and we want to avoid the influence of outliers. 


demo_table = (
    df_merged[df_merged["gendr"].isin(["F", "M", "U"])]
    .groupby("gendr")
    .agg(
        Clients=("client_id", "count"),
        Age_median=("clnt_age", "median"),
        Tenure_Years_Median=("clnt_tenure_yr", "median"),
        Tenure_Months_Median=("clnt_tenure_mnth", "median"),
        Balance_Median=("bal", "median"),
        Calls_6M_Median=("calls_6_mnth", "median"),
        Logons_6M_Median=("logons_6_mnth", "median"),
    )
    .round(2)
    .T
)

demo_table

gendr                       F         M        U
Clients               16258.0  16947.00  17280.0
Age_median               52.0     50.50     39.5
Tenure_Years_Median      14.0     14.00      6.0
Tenure_Months_Median    173.0    173.00     77.0
Balance_Median        71135.4  88460.55  51430.5
Calls_6M_Median           2.0      4.00      3.0
Logons_6M_Median          6.0      7.00      6.0

-  Who are the primary clients using this online process? Are the primary clients younger or older, new or long-standing?


    The online process is mainly used by middle-aged, long-standing clients. On average, users are around 47 years old and have been with Vanguard for about 12 years, which suggests a mature and established customer base rather than a newly acquired one. They hold generally substantial balances, although the distribution is skewed by a smaller group of high-balance clients, and they show moderate platform engagement with around 6 logons and 3 support calls in the last six months. Gender distribution is fairly balanced across the main groups, but the  U  category stands out as a younger and less-tenured segment.

In [182]:
demo_table_with_variation = (
    df_merged[df_merged["gendr"].isin(["F", "M", "U"])]
    .groupby(["Variation", "gendr"])
    .agg(
        Clients=("client_id", "count"),
        Age_Median=("clnt_age", "median"),
        Tenure_Years_Median=("clnt_tenure_yr", "median"),
        Tenure_Months_Median=("clnt_tenure_mnth", "median"),
        Balance_Median=("bal", "median"),
        Calls_6M_Median=("calls_6_mnth", "median"),
        Logons_6M_Median=("logons_6_mnth", "median"),
    )
    .round(2)
    .T
)

demo_table_with_variation

Variation              Control                         Test
gendr                        F        M         U         F        M        U
Clients                7542.00   7970.0   8014.00   8716.00   8977.0   9266.0
Age_Median               52.00     50.5     40.00     51.50     50.0     39.5
Tenure_Years_Median      14.00     14.0      6.00     14.00     14.0      6.0
Tenure_Months_Median    173.00    174.0     77.00    172.00    173.0     77.0
Balance_Median        70795.61  90075.6  51541.92  71446.28  86797.8  51321.1
Calls_6M_Median           2.00      4.0      3.00      2.00      3.0      3.0
Logons_6M_Median          6.00      7.0      6.00      6.00      7.0      6.0

The Control and Test groups are broadly similar across age, tenure, balance, calls, and logons when broken down by gender. This suggests the experiment groups were reasonably balanced at the begining so we can compare them equally later on.

In [184]:
group_sizes = df_merged["Variation"].value_counts()
print(group_sizes)

Variation
Test       26961
Control    23526
Name: count, dtype: int64

Test group seems to be around 3K bigger than control one, which might be important in the future when drawing conclusions

## Phase 2 — Performance Metrics

### Exploring customer journey

Let's explore to understand the customer journey in general as a process before deep diving further.

In [173]:
df_final_web_1_and_2_clean

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
637487,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27
637532,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17
637533,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31
637534,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23
637535,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20

In [174]:
web_merged = df_final_web_1_and_2_clean.merge(
    df_final_experiment_no_nulls,
    on="client_id",
    how="inner"
)

In [175]:
web_merged

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

Independently of the groups, customers are navigating through a process that is start>step1>step2>step3>confirm. Some of them go back and forth in the process, this should be considered too.

### Success Indicators


Calculate at least:

- **Completion Rate**: The proportion of users who reach the final 'confirm' step.

- **Time Spent on Each Step**: The average duration users spend on each step.

- **Error Rates**: If there's a step where users go back to a previous step, it may indicate confusion or an error. You should consider moving from a later step to an earlier one as an error.

#### Completion Rate

In [187]:
web_merged

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

In [189]:

total_clients = web_merged.groupby("Variation")["client_id"].nunique()

completed_clients = (
    web_merged[web_merged["process_step"] == "confirm"]
    .groupby("Variation")["client_id"]
    .nunique()
)

completion_rate = (completed_clients / total_clients * 100).round(2)

print(completion_rate)

Variation
Control    65.59
Test       69.29
Name: client_id, dtype: float64

So around 69% of the Test group has completed it vs a 66 % from control one

#### Time spent per step

In [190]:
# KPI 2: Time Spent on Each Step
# Calculate time duration (in seconds) spent on each step per visit
web_merged["time_spent_sec"] = (
    web_merged.groupby("visit_id")["date_time"].diff().dt.total_seconds()
)

# Filter out negative time or unrealistic long sessions (> 30 mins / 1800s)
valid_time_df = web_merged[
    (web_merged["time_spent_sec"] > 0) & (web_merged["time_spent_sec"] <= 1800)
]

# Calculate mean and median duration spent on each step
time_spent_summary = (
    valid_time_df.groupby(["Variation", "process_step"])["time_spent_sec"]
    .agg(
        mean_time_sec="mean",
        median_time_sec="median",
    )
    .round(2)
)

print("=== KPI 2: TIME SPENT PER STEP (SECONDS) ===")
print(time_spent_summary)

=== KPI 2: TIME SPENT PER STEP (SECONDS) ===
                        mean_time_sec  median_time_sec
Variation process_step
Control   confirm              598.67            483.0
          start                767.41            653.0
          step_1               606.68            433.0
          step_2               485.58            306.0
          step_3               487.27            291.0
Test      confirm              636.88            498.0
          start                684.07            576.0
          step_1               646.09            533.0
          step_2               564.37            430.0
          step_3               523.16            502.5